version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 197520012003
      MYSQL_DATABASE: todo_list
      DB_USER: root
      DB_PASSWORD: 197520012003
     

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--protocol", "tcp", "-h", "127.0.0.1", "--silent"]
      timeout: 20s
      interval: 5s
      retries: 10
      
  golang:
    image: golang:latest
    container_name: golang-container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    command: ["go", "run", "main.go"]
    depends_on:
      - mysql
   
    