version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: todo_list
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 20s
      interval: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  golang:
    image: golang:latest
    container_name: golang-container
    working_dir: /app
    volumes:
      - .:/app
      - ./ressources/config.yaml:/app/config.yaml
      - ./ressources/.env:/app/.env
    ports:
      - "9000:9000"
    command: ["sh", "-c", "echo $DB_PASSWORD && go run main.go"]
    depends_on:
      - mysql
      
    env_file:
      - ./ressources/.env

volumes:
  mysql_data:
